version: '3.9'

services:
  db:
    container_name: pf_db
    image: postgres:14-alpine
    restart: unless-stopped
    environment: # environment variables for the Postgres container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: # port exposed to the host machine
      - "5432:5432"
    volumes: # volume used to persist data
      - pgdata:/var/lib/postgresql/data


  kotlinapp:
    container_name: pf_backend
    restart: unless-stopped
    build: # this is the build context: .  
      context: .
      dockerfile: Dockerfile
      args: # these are the arguments that are passed to the dockerfile
        DB_URL: postgres
        PG_USER: postgres
        PG_PASSWORD: postgres
    ports: # port exposed to the host machine
      - "8080:8080"
    env_file:
      - .env
    depends_on: # this is the dependency on the db service
      - db


volumes:
  pgdata: